# This tester environment is generated by AI and the scenarios are written by the student

import subprocess
import time
import os
import hashlib
import socket
import random
import threading
import sys
from concurrent.futures import ThreadPoolExecutor

BINARY = "./ipk-rdt"
SERVER_PORT = 5555
PROXY_PORT = 6666

class AdvancedProxy:
    def __init__(self, listen_port, target_addr, target_port, loss=0, delay=0, jitter=0, corrupt=0, dup=0):
        self.listen_port = listen_port
        self.target_addr = target_addr
        self.target_port = target_port
        self.loss = loss / 100.0
        self.delay = delay / 1000.0
        self.jitter = jitter / 1000.0
        self.corrupt = corrupt / 100.0
        self.dup = dup / 100.0
        self.running = False
        self.client_address = None
        self.executor = ThreadPoolExecutor(max_workers=20)

    def start(self):
        infos = socket.getaddrinfo(self.target_addr, self.target_port, socket.AF_UNSPEC, socket.SOCK_DGRAM)
        family, socktype, proto, canonname, sockaddr = infos[0]

        self.sock = socket.socket(family, socket.SOCK_DGRAM)
        self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

        bind_addr = '::' if family == socket.AF_INET6 else '0.0.0.0'
        self.sock.bind((bind_addr, self.listen_port))

        self.sock.settimeout(0.1)
        self.running = True

        def process_and_send(d, target, apply_faults, wait_time):
            if apply_faults and self.corrupt > 0 and random.random() < self.corrupt:
                b_data = bytearray(d)
                b_data[random.randint(0, len(b_data)-1)] ^= 0xFF
                d = bytes(b_data)

            if wait_time > 0:
                time.sleep(max(0, wait_time))

            try:
                self.sock.sendto(d, target)
            except:
                pass

        def proxy_loop():
            while self.running:
                try:
                    data, addr = self.sock.recvfrom(4096)
                    is_from_server = (addr[1] == self.target_port)

                    if not is_from_server:
                        self.client_address = addr
                        dest = sockaddr
                    else:
                        if not self.client_address: continue
                        dest = self.client_address

                    if not is_from_server and random.random() < self.loss: continue

                    current_wait = self.delay
                    if not is_from_server and self.jitter > 0:
                        current_wait += random.uniform(-self.jitter, self.jitter)

                    count = 2 if (not is_from_server and random.random() < self.dup) else 1
                    for _ in range(count):
                        self.executor.submit(process_and_send, data, dest, not is_from_server, current_wait)

                except socket.timeout:
                    continue
                except Exception:
                    continue

        threading.Thread(target=proxy_loop, daemon=True).start()

    def stop(self):
        self.running = False
        self.executor.shutdown(wait=False)
        time.sleep(0.3)
        if hasattr(self, 'sock'):
            self.sock.close()

def run_scenario(name, size_mb, loss=0, delay=0, jitter=0, corrupt=0, dup=0, ipv6=False, use_pipes=False):
    print(f"  [{name:15}] ", end="", flush=True)
    addr = "::1" if ipv6 else "127.0.0.1"
    test_in, test_out = "test_in.bin", "test_out.bin"
    if os.path.exists(test_out): os.remove(test_out)

    data_to_send = os.urandom(int(size_mb * 1024 * 1024)) if size_mb > 0 else b""
    with open(test_in, "wb") as f: f.write(data_to_send)

    proxy = AdvancedProxy(PROXY_PORT, addr, SERVER_PORT, loss, delay, jitter, corrupt, dup)
    proxy.start()

    srv_cmd = [BINARY, "-s", "-p", str(SERVER_PORT)]
    clt_cmd = [BINARY, "-c", "-a", addr, "-p", str(PROXY_PORT)]

    received_data = b""
    start_t = time.time()

    try:
        if use_pipes:
            srv_proc = subprocess.Popen(srv_cmd + ["-o", "-"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            time.sleep(0.4)

            clt_proc = subprocess.Popen(clt_cmd + ["-i", "-"], stdin=subprocess.PIPE, stderr=subprocess.DEVNULL)

            def feed_client():
                try:
                    clt_proc.stdin.write(data_to_send)
                    clt_proc.stdin.close()
                except:
                    pass

            feeder = threading.Thread(target=feed_client)
            feeder.start()

            try:
                received_data, _ = srv_proc.communicate(timeout=15)
                clt_proc.wait(timeout=5)
            finally:
                feeder.join()
        else:
            srv_proc = subprocess.Popen(srv_cmd + ["-o", test_out], stderr=subprocess.DEVNULL)
            time.sleep(0.4)
            clt_proc = subprocess.Popen(clt_cmd + ["-i", test_in], stderr=subprocess.DEVNULL)

            clt_proc.wait(timeout=60)
            time.sleep(1.0)
            srv_proc.terminate()
            srv_proc.wait()

            if os.path.exists(test_out):
                with open(test_out, "rb") as f: received_data = f.read()

    except subprocess.TimeoutExpired:
        print("\033[91mTIMEOUT\033[0m ", end="")
        received_data = b"TIMEOUT"
        clt_proc.kill()
        srv_proc.kill()
    except Exception as e:
        print(f"\033[91mERROR: {e}\033[0m ", end="")
        received_data = b"ERROR"

    proxy.stop()

    passed = (received_data == data_to_send)
    status = "\033[92mPASS\033[0m" if passed else "\033[91mFAIL\033[0m"
    print(f"{status} ({time.time() - start_t:.1f}s)")
    return passed

if __name__ == "__main__":
    print("\n  Student automated tests:")
    print("  " + "─" * 50)

    results = [
        run_scenario("IPv4_Baseline", 0.5),
        run_scenario("IPv6_Baseline", 0.5, ipv6=True),
        run_scenario("EmptyInput_File", 0),
        run_scenario("Transfer_1MB", 1),
        run_scenario("Transfer_2MB", 2),
        run_scenario("Transfer_5MB", 5),
        run_scenario("Transfer_10MB", 10),
        run_scenario("Transfer_20MB", 20),
        run_scenario("Transfer_50MB", 50),
        run_scenario("Transfer_100MB", 100),
        run_scenario("Pipes_Mode_Test", 0.2, use_pipes=True),
        run_scenario("PacketLoss_15pct", 0.3, loss=15),
        run_scenario("Duplication_15pct", 0.3, dup=15),
        run_scenario("Jitter_Reorder_Test", 0.3, delay=20, jitter=20),
        run_scenario("Corruption_2pct", 0.2, corrupt=2),
        run_scenario("Stress_Test_Heavy", 2.0, loss=5, delay=10, dup=5),
        run_scenario("Extreme_Stress_Mode", 0.5, loss=10, delay=30, jitter=20, corrupt=1, dup=10)
    ]

    print("  " + "─" * 50)
    print(f"  Final Score: {sum(results)}/{len(results)}")
    if all(results): print("  ALL TESTS PASSED!")
    sys.exit(0 if all(results) else 1)